# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 218b50b07188a7a98f83f0d6faf7fee506ee9ca4177d770bec14efcca0cd8c1cee664b81bc034f877caf093d1952010c544c66af1643b28cd8c812f89fd24037

test:
  secret_key_base: 3219f576e73e0965fca1a3d1ab2bc71cc9ca3edfc1664e391b9236f610dd9b7681a6980dacc5b62c753b55639d5a60b662e9427f1630c2144e423ca2a0047e19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
